// Service page content. Copy adapted from the marketing pack (05-service-pages-copy.md).
// Changes from the pack: no bucket-truck claims (not owned yet), Strata mentioned
// only on About + FAQ, hours/insurance/email pulled from site.js.
const site = require("./site.js");

module.exports = [
  {
    slug: "tree-removal",
    name: "Tree Removal",
    card: "Dead, leaning, or in the way. Sectioned down safe, chipped, hauled.",
    title: "Tree Removal Baton Rouge | Safe Residential Removals",
    description: "Hazardous, dead, or oversized tree removal with cleanup. Serving EBR, Ascension & Livingston. Free on-site estimates: (225) 418-2720.",
    h1: "Tree Removal in Baton Rouge & Surrounding Parishes",
    intro: [
      "Need a tree gone? We remove dead, leaning, storm-damaged, and oversized trees from residential yards across Greater Baton Rouge. We section them down, chip what we can, haul the rest, and leave the site clean.",
    ],
    trustTail: "Certificate of insurance available before work starts.",
    whatWeDo: [
      "Full tree removal, from small yard trees to large hardwoods — scoped per job",
      "Hazardous and leaning trees near houses, fences, and driveways",
      "Dead tree removal",
      "Sectional takedown with ropes and controlled lowering when space is tight",
      "Chip and haul included in most scopes (confirmed on the estimate)",
      "Stump grinding as an add-on",
    ],
    note: "We don’t guess from the curb when the job is complex. If we need a closer look at lean, decay, or access, we say so on the visit.",
    process: [
      ["Details or call", "Photos help. Note power lines, fences, septic, and how close the tree is to the house."],
      ["On-site estimate", "We check the tree, drop zones, and equipment access. You get a written price."],
      ["Removal day", "Rig, cut, chip, load. We protect lawns and hardscape as the job requires."],
      ["Cleanup", "Brush and wood leave with us unless you want firewood rounds. Stump grinding same day or on a follow-up visit."],
    ],
    whenToCall: [
      "The tree is dead, hollow, or dropping large limbs",
      "It leans toward the house, garage, or the neighbor’s property",
      "Storm damage — cracked trunk, hanging limbs, roots lifting",
      "It’s in the way of a fence, addition, driveway, or pool",
      "You’re selling and the buyer or inspector flagged it",
    ],
    hazardNote: true,
    faq: [
      ["How much does tree removal cost in Baton Rouge?", "It depends on height, species, lean, access, and how close it is to structures. Call or send photos for a starting conversation — most jobs need an on-site look for a firm number."],
      ["Do you haul everything away?", "Yes on standard scopes — chips and wood leave with us. Want rounds left for firewood? Say so when we quote."],
      ["INSURANCE", ""],
      ["LICENSE", ""],
    ],
    ctaHeading: "Ready to get a number on that tree?",
    ctaButton: "Get a Free Estimate",
    related: ["stump-grinding", "tree-trimming", "emergency-storm"],
    areas: ["baton-rouge", "prairieville", "denham-springs"],
  },
  {
    slug: "tree-trimming",
    name: "Tree Trimming & Pruning",
    card: "Clear roofs and lines. Reduce storm risk. No harmful topping.",
    title: "Tree Trimming & Pruning Baton Rouge | Vertic Tree Works",
    description: "Clear roofs and lines, reduce storm risk, and shape trees the right way — no harmful topping. Free estimates: (225) 418-2720.",
    h1: "Tree Trimming & Pruning in Baton Rouge",
    intro: [
      "Overgrown limbs on the roof. Branches in the lines. A canopy that needs thinning before storm season. We trim and prune residential trees across Greater Baton Rouge — with a clear plan and no “top and hope.”",
    ],
    trustTail: "Cleanup included on quoted scopes.",
    whatWeDo: [
      "Crown cleaning — dead, dying, and broken limbs out",
      "Roof and structure clearance",
      "Driveway and sight-line clearance",
      "Selective thinning to cut wind load where it makes sense",
      "Crepe myrtle pruning done right — no knuckled-off stubs",
      "Storm-prep trimming before hurricane season",
    ],
    callout: {
      heading: "Roof-line clearance",
      body: "Limbs on shingles and gutters wear the roof, drop debris, and give squirrels a ramp. We cut back to proper points so the clearance holds — not a flat-top haircut that grows back thicker. Ask for it on its own or with a full trim.",
    },
    policy: {
      heading: "We don’t top trees",
      body: "Topping — cutting the whole crown back to stubs — makes a tree look neat for a season. Then it throws out fast, weakly attached sprouts, the big cuts decay, and you’ve got a bigger risk than you started with. If someone already topped yours, we’ll talk realistic options: restoration pruning, reduction where it makes sense, or removal if the tree is too far gone.",
    },
    education: {
      heading: "Louisiana tree care, in short",
      paras: [
        "Our trees take a lot: summer heat, soaked ground, droughts in between, and wind from fronts and Gulf systems. Stressed trees are the ones that decay and pick up disease, and dead wood and weak limb unions are what fail first when the wind comes.",
        "Good pruning deals with that before it’s an emergency: take out the dead and damaged wood, fix bad structure while limbs are small, keep weight off the roof, and leave enough canopy for the tree to stay healthy. That’s why we’ll sometimes tell you a tree can wait — and sometimes tell you it can’t.",
      ],
    },
    process: [
      ["Walk the tree", "Goals first: clearance, health, storm risk, appearance."],
      ["Written scope", "What comes off, what stays, and the price."],
      ["Trim day", "Bucket truck, lift, or climb — whatever the tree and the access call for. Cuts made with the tree’s structure in mind."],
      ["Chip and haul", "Yard left clean unless you want mulch left behind (confirmed on the estimate)."],
    ],
    whenToCall: [
      "Limbs rubbing the roof or gutters",
      "Branches blocking sidewalks, drives, or sight lines",
      "A heavy canopy you want lightened before storm season",
      "Crepe myrtles that need shaping — not “crepe murder”",
      "Dead wood hanging over where people walk or park",
    ],
    faq: [
      ["What’s the difference between trimming and pruning?", "People use both words. We mean selective cuts for clearance, structure, and risk — not random hacking. We’ll use plain language on your estimate."],
      ["Will you top my crepe myrtles?", "No. We can reduce and shape them properly. Topping looks neat for a month and costs you later."],
      ["How often should trees be trimmed?", "Depends on the species and how close they are to the house. Many yards do fine with a look every few years; storm prep is its own conversation. We’ll tell you if a tree can wait."],
    ],
    ctaHeading: "Clear the roof. Cut the risk. Keep the tree.",
    ctaButton: "Schedule a Trim Estimate",
    related: ["tree-removal", "emergency-storm", "stump-grinding"],
    areas: ["baton-rouge", "central", "zachary"],
  },
  {
    slug: "stump-grinding",
    name: "Stump Grinding",
    card: "Grind it out after removal or as a standalone job.",
    title: "Stump Grinding Baton Rouge | Vertic Tree Works",
    description: "Grind stumps after removal or as a standalone job. Ask about package pricing with tree removal. (225) 418-2720.",
    h1: "Stump Grinding in Baton Rouge & Nearby Cities",
    intro: [
      "Tree’s gone but the stump remains — trip hazard, mower problem, or just ugly. We grind stumps below grade so you can reseed, sod, or plant. Available with our removals or as a standalone visit.",
    ],
    trustTail: "Package pricing available with removal.",
    whatWeDo: [
      "Stump grinding after our tree removals — usually the same day",
      "Standalone stump grinding — stumps from other jobs welcome, we still need to see access",
      "Surface roots in the grind zone when discussed in the quote",
      "Grindings left as backfill or hauled off — your call on the estimate",
    ],
    note: "Grinding isn’t full root-ball excavation. If you need the stump dug out for construction, say so — that’s a different scope.",
    process: [
      ["Measure and access", "Stump diameter, height above grade, fences, irrigation, and underground utilities."],
      ["Quote", "Per stump, or packaged with a removal."],
      ["Grind", "Below grade to the depth we agree on."],
      ["Finish", "Grindings raked; hauled off if quoted. We’ll mark the spot if you plan to plant."],
    ],
    whenToCall: [
      "You just had a tree removed and want the stump gone",
      "Stumps in the lawn catching the mower",
      "You’re putting in sod, a patio, or a fence line",
      "Several stumps on one lot — ask about multi-stump pricing",
    ],
    faq: [
      ["How deep do you grind?", "Typically several inches below grade — enough for grass or shallow planting. Need deeper for a slab or driveway? Tell us on the visit."],
      ["Can you grind the same day as removal?", "Usually, yes. Once in a while access or scheduling pushes it to a follow-up visit — the quote will say which."],
      ["Do grindings kill the grass?", "Fresh chips aren’t good topsoil. We can leave them for you to use as mulch elsewhere, or haul them. Reseed or sod after the spot settles."],
    ],
    ctaHeading: "Add grinding to your removal — or book stumps alone.",
    ctaButton: "Get a Stump Quote",
    related: ["tree-removal", "tree-trimming"],
    areas: ["prairieville", "gonzales", "denham-springs"],
  },
  {
    slug: "emergency-storm",
    name: "Emergency & Storm",
    card: "Tree on the house, driveway, or fence? Call first.",
    title: "Emergency Tree Removal Baton Rouge | Storm Response",
    description: "Tree on the house or driveway? Call (225) 418-2720 for storm damage and hazard tree response across Greater Baton Rouge.",
    h1: "Emergency & Storm Tree Service in Greater Baton Rouge",
    emergency: true,
    intro: [
      "Tree on the house. Driveway blocked. A limb hanging over the kids’ play area after a storm. Call us. We’ll tell you what we can do and how fast we can get there.",
    ],
    trustTail: site.open247 ? "Open 24/7. Hazards come first." : "Hazards come first when we can respond.",
    whatWeDo: [
      "Trees or large limbs on houses, garages, and sheds",
      "Blocked driveways, sidewalks, and access",
      "Trees down on fences (we do the tree work — not the fence rebuild)",
      "Hanging limbs left after wind",
      "Storm cleanup: cut, chip, and haul hazardous debris from the yard",
      "Photos and an itemized invoice for your homeowner’s claim — we’re not adjusters, but we document the work",
    ],
    process: [
      ["Call first", "Tell us what’s been hit — house, car, lines."],
      ["Safety triage", "If power lines are involved, call the utility or 911 first. We don’t work around live lines."],
      ["Make it safe, then clear", "Sometimes that’s “stabilize now,” then full cleanup when access allows."],
      ["Cleanup and paperwork", "Debris hauled per the quote. Ask for our COI and an itemized invoice for insurance."],
    ],
    whenToCall: [
      "A tree or major limb on the roof or through a wall",
      "Your driveway or street access is blocked",
      "A tree on a vehicle",
      "A large hanging limb that could drop on people or property",
      "Hurricane or tropical storm debris that’s a real hazard — not just leaf cleanup",
    ],
    faq: [
      ["HOURS", ""],
      ["Will my insurance cover this?", "Homeowner’s policies often cover sudden storm damage, but every policy differs. We provide photos and an itemized invoice. Your adjuster decides coverage."],
      ["What if the tree is on the neighbor’s side?", "Property lines matter. We’ll talk through what’s yours to authorize. Don’t cut what you don’t own without agreement."],
    ],
    ctaHeading: "Tree down? Call first.",
    ctaButton: "Send photos instead",
    related: ["tree-removal", "tree-trimming"],
    areas: ["baton-rouge", "denham-springs", "prairieville"],
  },
  {
    slug: "land-clearing",
    name: "Land Clearing",
    card: "Lot and brush clearing. Site visit required.",
    optional: true,
    title: "Land & Lot Clearing Baton Rouge | Vertic Tree Works",
    description: "Lot clearing and brush removal for residential and light commercial sites. Request a site visit: (225) 418-2720.",
    h1: "Land & Lot Clearing in Greater Baton Rouge",
    intro: [
      "Building, opening up a back line, or clearing a grown-over lot? We clear trees and brush for residential and light sites when the job fits our crew and equipment. Site visit required — no curb quotes for clearing.",
    ],
    trustTail: "Scope set on-site.",
    whatWeDo: [
      "Residential lot clearing",
      "Selective clearing — keep the trees you want",
      "Brush and undergrowth removal",
      "Fence-line clearing for access and visibility (trees and brush only)",
      "Haul-off, or burning only where local rules allow and it’s in the quote",
    ],
    note: "Not typically: large forestry mulching, wetland work, or municipal contracts unless separately agreed.",
    process: [
      ["Site visit", "Walk the boundaries, drainage, and what stays versus what goes."],
      ["Written scope", "Acreage isn’t everything — density and access drive the price."],
      ["Clear and haul", "Per the agreement."],
      ["Leave-ready", "Rough grade and debris standard as quoted — not finish landscaping unless specified."],
    ],
    whenToCall: [
      "You’re buying or building and need trees and brush off a lot",
      "An overgrown side yard or back line",
      "You want selected trees down and the rest left standing",
      "Clearing the edge of a light commercial pad or lot",
    ],
    faq: [
      ["Do you clear by the acre?", "We price by what’s on the ground and how we can reach it — not a flat per-acre guess from a map pin."],
      ["Can you leave certain trees?", "Yes. Mark the keepers before we start. We’ll flag any that are risky to leave."],
      ["Do you install fences after clearing?", "No — Vertic is trees and brush only. We’ll leave the line clear for whoever builds the fence."],
    ],
    ctaHeading: "Book a site visit. We’ll walk it and price it.",
    ctaButton: "Request a Clearing Visit",
    related: ["tree-removal", "stump-grinding"],
    areas: ["gonzales", "prairieville", "zachary"],
  },
];
